### PR TITLE
Dart Null Safety Compatibility

### LINKED ISSUE #24: Error on `throwNullError`
**Describe the bug**
```
Running Gradle task 'assembleDebug'...
../../.pub-cache/hosted/pub.dartlang.org/wave-0.1.0/lib/config.dart:46:13: Error: Method not found: 'throwNullError'.
            throwNullError('custom', 'colors` or `gradients');
            ^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/wave-0.1.0/lib/config.dart:60:13: Error: Method not found: 'throwNullError'.
            throwNullError('custom', 'durations');
            ^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/wave-0.1.0/lib/config.dart:66:13: Error: Method not found: 'throwNullError'.
            throwNullError('custom', 'heightPercentages');
```

**To Reproduce**
1. When try run code on android studio
2. flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.24.0-8.0.pre.178, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-IL)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.51.0)
[✓] Connected device (2 available)

• No issues found!
```

**Expected behavior**
Can't run app on android studio

**Screenshots**
Screen Shot 2020-11-10 at 14 52 16

**Smartphone (please complete the following information):**
 - Device: Android SDK build for x86

**Additional context**
Crashed on build application

### PR DESCRIPTION
**Pull request by searchy2**
Fixes #24 , #22

### CODE REVIEW

**Review by callawey — APPROVED** [review]
Null Safety for throwNullError applied correctly

**Comment by tim232385** [comment]
please... fix it

**Comment by searchy2** [comment]
Can this PR be merged?

**Review by mohammadne — APPROVED** [review]
Null Safety for throwNullError applied correctly

**Review by ashamnx — APPROVED** [review]

**Comment by searchy2** [comment]
Merging is still blocked. 
MaxthonSnap20201208101113

**Review by GGuinea — APPROVED** [review]

**Comment by GGuinea** [comment]
Will be good to merge those changes :)

**Comment by nuno84** [comment]
Up!

**Comment by searchy2** [comment]
There's more reviewers here than in Google's repo. 
Can someone please help merge this PR?

**Review by pinpong — COMMENTED** [review]
lgtm

**Review by npereira-jc — APPROVED** [review]

**Review by RaineCode178 — APPROVED** [review]

**Review by CristianTorrado — APPROVED** [review]
Works good :) Thanks 👍

**Comment by searchy2** [comment]
Why is merging still blocked? Numerous people have reviewed this PR. I'll be closing this PR if it does not get merged soon.

**Comment by AyushBherwani1998** [comment]
@searchy2 Only the member of organization or those who have write access to the repository can approve your request :(

**Comment by AyushBherwani1998** [comment]
Hey @RockerFlower, can you please review this PR? Thanks :)

**Review by rockar06 — APPROVED** [review]

**Comment by ubuntudroid** [comment]
Shouldn't this now be fine to be merged?

**Comment by zjamshidi** [comment]
waiting for it

**Comment by danieramiz** [comment]
This plugin it's lost in space
abandoned!
6 months since the last update

**Review by AbdOoSaed — APPROVED** [review]

**Review by danieramiz — APPROVED** [review]

**Comment by AbdOoSaed** [comment]
thank @searchy2 I used ur fork and it working good

```yaml
  wave:
    git:
      url: git://github.com/searchy2/wave.git
```

**Review by HektorCyC — APPROVED** [review]

**Review by HektorCyC — APPROVED** [review]
lgtm

**Review by fgarcia92 — APPROVED** [review]

**Review by clirimfurriku — APPROVED** [review]

**Comment by RockerFlower** [comment]
@searchy2 @callawey @tim232385 @mohammadne @ashamnx @GGuinea @nuno84 @pinpong @npereira-jc @RaineCode178 @CristianTorrado @AyushBherwani1998 @rockar06 @ubuntudroid @zjamshidi @danieramiz @AbdOoSaed @danieramiz @HektorCyC @fgarcia92 @clirimfurriku 

I am very sorry! Due to some personal matters, I haven't logged in to GitHub for a long time, which wasted your time. I will restart the maintenance of this plugin in the near future. Sorry again!

**Comment by ubuntudroid** [comment]
@RockerFlower no worries, after all this is a free (and open source) library and you are doing this in your spare time, so no need to be sorry! Instead, let me thank you for picking this up again. 🙏

**Comment by ashamnx** [comment]
Welcome back and I hope everything is well now.

**Pull request merged**
